list = {"apple", "avocado", "apricot",
"banana", "blackberry", "blueberry", "boysenberry",
"cherry", "cantaloupe", "cranberry", "coconut", "cucumber", "currant",
"date", "durian", "dragonfruit",
"elderberry",
"fig",
"grapefruit", "guava", "grape",
"honeydew", "honeyberry",
"jackfruit",
"kiwi", "kumquat",
"lemon", "lime", "lychee", "longan",
"mango", "mangosteen", "mandarin",
"nectarine",
"orange", "olive",
"pineapple", "papaya", "plum", "passion-fruit", "peach", "pear",
   "persimmon", "prune", "pummelo", "pomegranate", "pluot", "plantain",
"raspberry", "rose-apple", "rambutan",
"strawberry", "star-fruit", "sapote", "soursop", "sugar-apple", "star-apple",
"tangerine", "tomato", "tamarind",
"watermelon",
}